exports.skills = [
  'Algorithms',
  'Analytical Skills',
  'Big Data',
  'Calculating',
  'Compiling Statistics',
  'Data Analytics',
  'Data Mining',
  'Database Design',
  'Database Management',
  'Documentation',
  'Modeling',
  'Modification',
  'Needs Analysis',
  'Quantitative Research',
  'Quantitative Reports',
  'Statistical Analysis',
  'Applications',
  'Certifications',
  'Coding',
  'Computing',
  'Configuration',
  'Customer Support',
  'Debugging',
  'Design',
  'Development',
  'Hardware',
  'Implementation',
  'Information Technology',
  'Infrastructure',
  'Languages',
  'Maintenance',
  'Network Architecture',
  'Network Security',
  'Networking',
  'New Technologies',
  'Operating Systems',
  'Programming',
  'Restoration',
  'Security',
  'Servers',
  'Software',
  'Solution Delivery',
  'Storage',
  'Structures',
  'Systems Analysis',
  'Technical Support',
  'Technology',
  'Testing',
  'Tools',
  'Training',
  'Troubleshooting',
  'Usability',
  'Benchmarking',
  'Budget Planning',
  'Engineering',
  'Fabrication',
  'Following Specifications',
  'Operations',
  'Performance Review',
  'Project Planning',
  'Quality Assurance',
  'Quality Control',
  'Scheduling',
  'Task Delegation',
  'Task Management',
  'Blogging',
  'Digital Photography',
  'Digital Media',
  'Facebook',
  'Instagram',
  'Networking',
  'Pinterest',
  'SEO',
  'Social Media Platforms',
  'Twitter',
  'Web Analytics',
  'Client Relations',
  'Email',
  'Requirements Gathering',
  'Research',
  'Subject Matter Experts (SMEs)',
  'Technical Documentation',
];

exports.courses = [
  'CS',
  'CV',
  'ECE',
  'IT',
  'BA',
  'BSc',
  'BBA',
  'B.Ed',
  'B.Com',
  'PGD',
  'MBA',
  'MA',
  'MSc',
  'M.Com',
];

exports.collegeRecords = [
  {
    id: 1,
    name: 'Rollins College',
    city: 'Portland',
    state: 'Oregon',
    country: 'United States',
    latitude: 45.5287,
    longitude: -122.6363,
  },
  {
    id: 2,
    name: 'University of New England',
    city: 'Columbus',
    state: 'Georgia',
    country: 'United States',
    latitude: 32.491,
    longitude: -84.8741,
  },
  {
    id: 3,
    name: "St. Martin's College",
    city: 'San Antonio',
    state: 'Texas',
    country: 'United States',
    latitude: 29.4375,
    longitude: -98.4616,
  },
  {
    id: 4,
    name: 'University of New Orleans',
    city: 'Omaha',
    state: 'Nebraska',
    country: 'United States',
    latitude: 41.249,
    longitude: -96.0274,
  },
  {
    id: 5,
    name: 'West Virginia Wesleyan College',
    city: 'Saint Louis',
    state: 'Missouri',
    country: 'United States',
    latitude: 38.6531,
    longitude: -90.2435,
  },
  {
    id: 6,
    name: 'Ouachita Baptist University',
    city: 'New York City',
    state: 'New York',
    country: 'United States',
    latitude: 40.7808,
    longitude: -73.9772,
  },
  {
    id: 7,
    name: 'Manhattanville College',
    city: 'Pasadena',
    state: 'California',
    country: 'United States',
    latitude: 33.7866,
    longitude: -118.2987,
  },
  {
    id: 8,
    name: 'University of Connecticut Health Center',
    city: 'Fayetteville',
    state: 'North Carolina',
    country: 'United States',
    latitude: 35.0583,
    longitude: -79.008,
  },
  {
    id: 9,
    name: 'University of Tennessee - Memphis',
    city: 'Memphis',
    state: 'Tennessee',
    country: 'United States',
    latitude: 35.2017,
    longitude: -89.9715,
  },
  {
    id: 10,
    name: 'Pikeville College',
    city: 'Sarasota',
    state: 'Florida',
    country: 'United States',
    latitude: 27.1675,
    longitude: -82.381,
  },
  {
    id: 11,
    name: 'South Carolina State University',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    country: 'United States',
    latitude: 40.0018,
    longitude: -75.1179,
  },
  {
    id: 12,
    name: 'Notre Dame College of Ohio',
    city: 'Pompano Beach',
    state: 'Florida',
    country: 'United States',
    latitude: 26.1457,
    longitude: -80.4483,
  },
  {
    id: 13,
    name: 'Trinity College Connecticut',
    city: 'Chicago',
    state: 'Illinois',
    country: 'United States',
    latitude: 41.8119,
    longitude: -87.6873,
  },
  {
    id: 14,
    name: 'Community College of Denver',
    city: 'San Bernardino',
    state: 'California',
    country: 'United States',
    latitude: 34.84,
    longitude: -115.9671,
  },
  {
    id: 15,
    name: 'Rasmussen College',
    city: 'New Orleans',
    state: 'Louisiana',
    country: 'United States',
    latitude: 29.9686,
    longitude: -90.0646,
  },
  {
    id: 16,
    name: 'Asbury College',
    city: 'Cincinnati',
    state: 'Ohio',
    country: 'United States',
    latitude: 39.2663,
    longitude: -84.5221,
  },
  {
    id: 17,
    name: 'University of North Carolina at Chapel Hill',
    city: 'Anniston',
    state: 'Alabama',
    country: 'United States',
    latitude: 33.7358,
    longitude: -85.7933,
  },
  {
    id: 18,
    name: 'Hallelujah Coast University',
    city: 'Wilmington',
    state: 'Delaware',
    country: 'United States',
    latitude: 39.5645,
    longitude: -75.597,
  },
  {
    id: 19,
    name: 'University of Evansville',
    city: 'Fullerton',
    state: 'California',
    country: 'United States',
    latitude: 33.8994,
    longitude: -117.9063,
  },
  {
    id: 20,
    name: 'ICT College',
    city: 'Orlando',
    state: 'Florida',
    country: 'United States',
    latitude: 28.5289,
    longitude: -81.4787,
  },
  {
    id: 21,
    name: 'Mills Grae University',
    city: 'Macon',
    state: 'Georgia',
    country: 'United States',
    latitude: 32.8067,
    longitude: -83.6913,
  },
  {
    id: 22,
    name: 'Moravian College',
    city: 'Reston',
    state: 'Virginia',
    country: 'United States',
    latitude: 38.8318,
    longitude: -77.2888,
  },
  {
    id: 23,
    name: 'William Penn College',
    city: 'New York City',
    state: 'New York',
    country: 'United States',
    latitude: 40.7808,
    longitude: -73.9772,
  },
  {
    id: 24,
    name: 'Shawnee State University',
    city: 'Houston',
    state: 'Texas',
    country: 'United States',
    latitude: 29.6297,
    longitude: -95.4382,
  },
  {
    id: 25,
    name: 'Siena College',
    city: 'Washington',
    state: 'District of Columbia',
    country: 'United States',
    latitude: 38.8952,
    longitude: -77.0365,
  },
  {
    id: 26,
    name: 'DeVry Institute of Technology, DuPage',
    city: 'Houston',
    state: 'Texas',
    country: 'United States',
    latitude: 29.834,
    longitude: -95.4342,
  },
  {
    id: 27,
    name: 'Austin College',
    city: 'Chicago',
    state: 'Illinois',
    country: 'United States',
    latitude: 41.9699,
    longitude: -87.7603,
  },
  {
    id: 28,
    name: 'Lynn University',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    country: 'United States',
    latitude: 40.5051,
    longitude: -80.1155,
  },
  {
    id: 29,
    name: 'Western State College',
    city: 'Saint Petersburg',
    state: 'Florida',
    country: 'United States',
    latitude: 27.6705,
    longitude: -82.7119,
  },
  {
    id: 30,
    name: 'International Academy of  Merchandising and Design Tampa',
    city: 'Hampton',
    state: 'Virginia',
    country: 'United States',
    latitude: 37.0318,
    longitude: -76.3199,
  },
  {
    id: 31,
    name: "Randolph-Macon Woman's College",
    city: 'Danbury',
    state: 'Connecticut',
    country: 'United States',
    latitude: 41.3089,
    longitude: -73.3637,
  },
  {
    id: 32,
    name: 'Maine College of Art',
    city: 'Madison',
    state: 'Wisconsin',
    country: 'United States',
    latitude: 43.0696,
    longitude: -89.4239,
  },
  {
    id: 33,
    name: 'Columbia Commonwealth University',
    city: 'Lakeland',
    state: 'Florida',
    country: 'United States',
    latitude: 28.072,
    longitude: -81.9609,
  },
  {
    id: 34,
    name: 'Michigan Technological University',
    city: 'Staten Island',
    state: 'New York',
    country: 'United States',
    latitude: 40.6324,
    longitude: -74.1172,
  },
  {
    id: 35,
    name: 'College of Charleston',
    city: 'Lincoln',
    state: 'Nebraska',
    country: 'United States',
    latitude: 40.9317,
    longitude: -96.6045,
  },
  {
    id: 36,
    name: 'St. Olaf College',
    city: 'Hamilton',
    state: 'Ohio',
    country: 'United States',
    latitude: 39.441,
    longitude: -84.5757,
  },
  {
    id: 37,
    name: 'Iowa Wesleyan College',
    city: 'Durham',
    state: 'North Carolina',
    country: 'United States',
    latitude: 36.0218,
    longitude: -78.9478,
  },
  {
    id: 38,
    name: 'Amber University',
    city: 'Lubbock',
    state: 'Texas',
    country: 'United States',
    latitude: 33.61,
    longitude: -101.8213,
  },
  {
    id: 39,
    name: 'Logan College of Chiropractic',
    city: 'Wichita',
    state: 'Kansas',
    country: 'United States',
    latitude: 37.6379,
    longitude: -97.2613,
  },
  {
    id: 40,
    name: 'California Coast University',
    city: 'Lansing',
    state: 'Michigan',
    country: 'United States',
    latitude: 42.5992,
    longitude: -84.372,
  },
  {
    id: 41,
    name: 'Ohio State University - Marion',
    city: 'Orlando',
    state: 'Florida',
    country: 'United States',
    latitude: 28.5663,
    longitude: -81.2608,
  },
  {
    id: 42,
    name: 'Hampton University',
    city: 'Chicago',
    state: 'Illinois',
    country: 'United States',
    latitude: 41.8119,
    longitude: -87.6873,
  },
  {
    id: 43,
    name: 'Butler University',
    city: 'Tulsa',
    state: 'Oklahoma',
    country: 'United States',
    latitude: 36.3024,
    longitude: -95.9605,
  },
  {
    id: 44,
    name: 'Peru State College',
    city: 'Jamaica',
    state: 'New York',
    country: 'United States',
    latitude: 40.6914,
    longitude: -73.8061,
  },
  {
    id: 45,
    name: 'Oregon Health Sciences University',
    city: 'Edmond',
    state: 'Oklahoma',
    country: 'United States',
    latitude: 35.6665,
    longitude: -97.4798,
  },
  {
    id: 46,
    name: "St. Mary's College of Maryland",
    city: 'Louisville',
    state: 'Kentucky',
    country: 'United States',
    latitude: 38.189,
    longitude: -85.6768,
  },
  {
    id: 47,
    name: 'Northern Virginia Community College',
    city: 'Birmingham',
    state: 'Alabama',
    country: 'United States',
    latitude: 33.5446,
    longitude: -86.9292,
  },
  {
    id: 48,
    name: 'University of Tennessee - Martin',
    city: 'Arlington',
    state: 'Virginia',
    country: 'United States',
    latitude: 38.8545,
    longitude: -77.052,
  },
  {
    id: 49,
    name: 'Salve Regina University',
    city: 'Houston',
    state: 'Texas',
    country: 'United States',
    latitude: 29.834,
    longitude: -95.4342,
  },
  {
    id: 50,
    name: 'Mid-Continent Baptist Bible College',
    city: 'Nashville',
    state: 'Tennessee',
    country: 'United States',
    latitude: 36.1866,
    longitude: -86.7852,
  },
  {
    id: 51,
    name: 'City University of New York, Queens College',
    city: 'New York City',
    state: 'New York',
    country: 'United States',
    latitude: 40.7808,
    longitude: -73.9772,
  },
  {
    id: 52,
    name: 'Gemological Institute of America',
    city: 'Myrtle Beach',
    state: 'South Carolina',
    country: 'United States',
    latitude: 33.7377,
    longitude: -78.9787,
  },
  {
    id: 53,
    name: 'Boston College',
    city: 'Kansas City',
    state: 'Missouri',
    country: 'United States',
    latitude: 39.2627,
    longitude: -94.697,
  },
  {
    id: 54,
    name: 'Southern Connecticut State University',
    city: 'Cedar Rapids',
    state: 'Iowa',
    country: 'United States',
    latitude: 41.9804,
    longitude: -91.7098,
  },
  {
    id: 55,
    name: 'New England School of Law',
    city: 'New York City',
    state: 'New York',
    country: 'United States',
    latitude: 40.7808,
    longitude: -73.9772,
  },
  {
    id: 56,
    name: 'Antioch University',
    city: 'Tacoma',
    state: 'Washington',
    country: 'United States',
    latitude: 47.0662,
    longitude: -122.1132,
  },
  {
    id: 57,
    name: 'The Boston Conservatory',
    city: 'Elizabeth',
    state: 'New Jersey',
    country: 'United States',
    latitude: 40.6747,
    longitude: -74.2239,
  },
  {
    id: 58,
    name: 'University of Mississippi Medical Center',
    city: 'Edmond',
    state: 'Oklahoma',
    country: 'United States',
    latitude: 35.6665,
    longitude: -97.4798,
  },
  {
    id: 59,
    name: 'Sage Graduate School',
    city: 'Oakland',
    state: 'California',
    country: 'United States',
    latitude: 37.6802,
    longitude: -121.9215,
  },
  {
    id: 60,
    name: 'Goldey-Beacom College',
    city: 'Glendale',
    state: 'Arizona',
    country: 'United States',
    latitude: 33.5291,
    longitude: -112.2482,
  },
  {
    id: 61,
    name: 'Barry University',
    city: 'Sioux City',
    state: 'Iowa',
    country: 'United States',
    latitude: 42.4011,
    longitude: -96.372,
  },
  {
    id: 62,
    name: 'University of the Sciences in Philadelphia',
    city: 'Reston',
    state: 'Virginia',
    country: 'United States',
    latitude: 38.8318,
    longitude: -77.2888,
  },
  {
    id: 63,
    name: 'Middle Tennessee State University',
    city: 'Albuquerque',
    state: 'New Mexico',
    country: 'United States',
    latitude: 35.0443,
    longitude: -106.6729,
  },
  {
    id: 64,
    name: 'Baker College of Mount Clemens',
    city: 'Birmingham',
    state: 'Alabama',
    country: 'United States',
    latitude: 33.5446,
    longitude: -86.9292,
  },
  {
    id: 65,
    name: 'Pacifica Graduate Institute',
    city: 'Cleveland',
    state: 'Ohio',
    country: 'United States',
    latitude: 41.6857,
    longitude: -81.6728,
  },
  {
    id: 66,
    name: 'Spertus Institute of Jewish Studies',
    city: 'Tulsa',
    state: 'Oklahoma',
    country: 'United States',
    latitude: 36.1398,
    longitude: -96.0297,
  },
  {
    id: 67,
    name: 'University of St. Thomas, St. Paul',
    city: 'Miami',
    state: 'Florida',
    country: 'United States',
    latitude: 25.5584,
    longitude: -80.4582,
  },
  {
    id: 68,
    name: 'Moore College of Art and Design',
    city: 'Chicago',
    state: 'Illinois',
    country: 'United States',
    latitude: 41.8756,
    longitude: -87.6378,
  },
  {
    id: 69,
    name: 'Institute of Clinical Social Work',
    city: 'Miami',
    state: 'Florida',
    country: 'United States',
    latitude: 25.5593,
    longitude: -80.3483,
  },
  {
    id: 70,
    name: 'Texas Southern University',
    city: 'Nashville',
    state: 'Tennessee',
    country: 'United States',
    latitude: 36.1379,
    longitude: -86.741,
  },
  {
    id: 71,
    name: 'Lipscomb University',
    city: 'Shreveport',
    state: 'Louisiana',
    country: 'United States',
    latitude: 32.6076,
    longitude: -93.7526,
  },
  {
    id: 72,
    name: 'Brigham Young University',
    city: 'Alexandria',
    state: 'Virginia',
    country: 'United States',
    latitude: 38.7192,
    longitude: -77.1073,
  },
  {
    id: 73,
    name: "O'More College of Design",
    city: 'Colorado Springs',
    state: 'Colorado',
    country: 'United States',
    latitude: 38.8152,
    longitude: -104.7703,
  },
  {
    id: 74,
    name: 'Wright State University',
    city: 'Tucson',
    state: 'Arizona',
    country: 'United States',
    latitude: 32.2138,
    longitude: -110.824,
  },
  {
    id: 75,
    name: 'Xavier University',
    city: 'Oklahoma City',
    state: 'Oklahoma',
    country: 'United States',
    latitude: 35.421,
    longitude: -97.5616,
  },
  {
    id: 76,
    name: 'Rocky Mountain College',
    city: 'Lubbock',
    state: 'Texas',
    country: 'United States',
    latitude: 33.571,
    longitude: -101.8507,
  },
  {
    id: 77,
    name: 'Kent State University - Tuscarawas',
    city: 'Houston',
    state: 'Texas',
    country: 'United States',
    latitude: 29.7179,
    longitude: -95.4263,
  },
  {
    id: 78,
    name: 'Columbia International University',
    city: 'Pompano Beach',
    state: 'Florida',
    country: 'United States',
    latitude: 26.1457,
    longitude: -80.4483,
  },
  {
    id: 79,
    name: 'Westminster College Fulton',
    city: 'Peoria',
    state: 'Illinois',
    country: 'United States',
    latitude: 40.692,
    longitude: -89.5887,
  },
  {
    id: 80,
    name: 'University of the South',
    city: 'Houston',
    state: 'Texas',
    country: 'United States',
    latitude: 29.7543,
    longitude: -95.3609,
  },
  {
    id: 81,
    name: 'Dhinchak Leo College',
    city: 'Seattle',
    state: 'Washington',
    country: 'United States',
    latitude: 47.6339,
    longitude: -122.3476,
  },
  {
    id: 82,
    name: 'Southern California Institute of Architecture',
    city: 'Jackson',
    state: 'Mississippi',
    country: 'United States',
    latitude: 32.3113,
    longitude: -90.3972,
  },
  {
    id: 83,
    name: 'Florida Metropolitan University, Tampa College',
    city: 'Cleveland',
    state: 'Ohio',
    country: 'United States',
    latitude: 41.6857,
    longitude: -81.6728,
  },
  {
    id: 84,
    name: 'American Military University',
    city: 'Saint Petersburg',
    state: 'Florida',
    country: 'United States',
    latitude: 27.8918,
    longitude: -82.7248,
  },
  {
    id: 85,
    name: 'Detroit College of Business - Flint',
    city: 'Buffalo',
    state: 'New York',
    country: 'United States',
    latitude: 42.7684,
    longitude: -78.8871,
  },
  {
    id: 86,
    name: 'University of Southern Mississippi',
    city: 'Minneapolis',
    state: 'Minnesota',
    country: 'United States',
    latitude: 44.9034,
    longitude: -93.374,
  },
  {
    id: 87,
    name: 'Yorker International University',
    city: 'Boise',
    state: 'Idaho',
    country: 'United States',
    latitude: 43.4599,
    longitude: -116.244,
  },
  {
    id: 88,
    name: 'Texas Tech University',
    city: 'Winston Salem',
    state: 'North Carolina',
    country: 'United States',
    latitude: 36.0275,
    longitude: -80.2073,
  },
  {
    id: 89,
    name: 'Oklahoma Christian University',
    city: 'Boston',
    state: 'Massachusetts',
    country: 'United States',
    latitude: 42.3253,
    longitude: -71.1122,
  },
  {
    id: 90,
    name: 'Johnson & Wales University',
    city: 'Oakland',
    state: 'California',
    country: 'United States',
    latitude: 37.799,
    longitude: -122.2337,
  },
  {
    id: 91,
    name: 'Columbia College South Carolina',
    city: 'Atlanta',
    state: 'Georgia',
    country: 'United States',
    latitude: 33.7488,
    longitude: -84.3883,
  },
  {
    id: 92,
    name: 'Villa Julie College',
    city: 'New York City',
    state: 'New York',
    country: 'United States',
    latitude: 40.7262,
    longitude: -73.9796,
  },
  {
    id: 93,
    name: 'Armstrong Atlantic State University',
    city: 'Memphis',
    state: 'Tennessee',
    country: 'United States',
    latitude: 35.2017,
    longitude: -89.9715,
  },
  {
    id: 94,
    name: 'St. Leo College',
    city: 'New York City',
    state: 'New York',
    country: 'United States',
    latitude: 40.6964,
    longitude: -74.0253,
  },
  {
    id: 95,
    name: 'Savannah State University',
    city: 'Bozeman',
    state: 'Montana',
    country: 'United States',
    latitude: 45.7246,
    longitude: -111.1238,
  },
  {
    id: 96,
    name: 'University of California, Hastings College of Law',
    city: 'Saint Louis',
    state: 'Missouri',
    country: 'United States',
    latitude: 38.6531,
    longitude: -90.2435,
  },
  {
    id: 97,
    name: 'Oakland City University',
    city: 'Baltimore',
    state: 'Maryland',
    country: 'United States',
    latitude: 39.2847,
    longitude: -76.6205,
  },
  {
    id: 98,
    name: 'Sanford-Brown Institute',
    city: 'Sioux Falls',
    state: 'South Dakota',
    country: 'United States',
    latitude: 43.5486,
    longitude: -96.6332,
  },
  {
    id: 99,
    name: 'Shorter College',
    city: 'New York City',
    state: 'New York',
    country: 'United States',
    latitude: 40.7105,
    longitude: -74.0163,
  },
  {
    id: 100,
    name: 'Concordia College, Ann Arbor',
    city: 'Lees Summit',
    state: 'Missouri',
    country: 'United States',
    latitude: 38.8518,
    longitude: -94.3944,
  },
];
